name: Add to changelog
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[CHANGE]')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true
      - name: Append changelog file
        uses: slegare/write-file-action@1.0.2
        with:
          path: changelog-1.20.1.txt
          write-mode: append
          empty-line-eof: true
          contents: |
            - ${{ github.event.head_commit.message }}
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GIT_TOKEN}}
          branch: ${{ github.ref }}
          force: true
